#!/bin/sh
#
# This script will set preferences on MacOS

source $DOTHOME/lib/common

set_macos_preferences() {
    if [ "$(uname -s)" != "Darwin" ]
    then
        return 0
    fi
    user "Set MacOS preferences? (y/n)"
    read -s -n 1 response
    if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then

        # Close any open System Preferences panes, to prevent them from overriding settings we’re about to change
        osascript -e 'tell application "System Preferences" to quit'

        # Ask for the administrator password upfront
        sudo -v

        # Keep-alive: update existing `sudo` time stamp until `.macos` has finished
        while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

        #########

        success "Set a blazingly fast keyboard repeat rate"
        defaults write NSGlobalDomain KeyRepeat -int 2

        success "Set a shorter delay until key repeat"
        defaults write NSGlobalDomain InitialKeyRepeat -int 15

        success "Enabled the Safari debug menu"
        defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

        success "Enabled the Develop menu and the Web Inspector in Safari"
        defaults write com.apple.Safari IncludeDevelopMenu -bool true
        defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
        defaults write com.apple.Safari "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" -bool true

        success "Set the the path bar in Finder to show"
        defaults write com.apple.finder ShowPathbar -bool true

        success "Set the status bar in Finder to show"
        defaults write com.apple.finder ShowStatusBar -bool true

        success "Set the indicator lights for open applications in the Dock to show"
        defaults write com.apple.dock show-process-indicators -bool true

        success "Set the mouse scroll direction"
        defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

        success "Set all processes in Activity Monitor to show by default"
        defaults write com.apple.ActivityMonitor ShowCategory -int 100

        success "Set the save panel to expand by default"
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

        success "Added a context menu item for showing the Web Inspector in web views"
        defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

        success "Disabled the annoying backswipe in Chrome"
        defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
        defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false

        success "Set the printing preferences to quit when finished"
        defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

        success "Using the system-native print preview dialog in Chrome"
        defaults write com.google.Chrome DisablePrintPreview -bool true
        defaults write com.google.Chrome.canary DisablePrintPreview -bool true

        success "Set to reveal IP address, hostname, OS version, etc. when clicking the clock in the login window"
        sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostsuccess HostName

        success "Set to 24-hour clock"
        defaults write com.apple.menuextra.clock DateFormat -string 'EEE MMM d  H:mm:ss'

        success "Set the computer to restart automatically on freeze"
        sudo systemsetup -setrestartfreeze on

        success "Disabled smart quotes (annoying when writing code)"
        defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

        success "Disabled smart dashes (annoying when writing code)"
        defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

        success "Set software updates to check daily instead of just once per week"
        defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

        success "Set the printer app to quit automatically once the print jobs complete"
        defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

        success "Set Finder to show all file extensions"
        defaults write NSGlobalDomain AppleShowAllExtensions -bool true

        success "Set Finder to show the full POSIX path in the title"
        defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

        success "Disabled the warning when changing a file extension"
        defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

        success "Set Finder to use column view everywhere"
        defaults write com.apple.finder FXPreferredViewStyle Clmv

        success "Disabled writing DS_Store files to network drives"
        defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

        success "Set to show the Library folder"
        chflags nohidden ~/Library

        success "Preventing Photos from opening every time a device is plugged in"
        defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

        user "Enable tap-to-click? (y/n)"
        read -s -n 1 response
        if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
            defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
            defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
            defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
        fi

        user "Save to disk instead of iCloud by default? (y/n)"
        read -s -n 1 response
        if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
            defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
        fi

        user "Disable the sudden motion sensor (it's not useful for SSDs)? (y/n)"
        read -s -n 1 response
        if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
            sudo pmset -a sms 0
        fi

    fi
}

