#!/bin/sh
#
# This script will install Homebrew/Linuxbrew if it's not already present.

source $DOTHOME/lib/common

function install_brew () {
    if test ! $(which brew)
    then
        user "Install Homebrew/Linuxbrew? (y/n)"
        read -s -n 1 response
        if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then

            info "Installing Homebrew"

            if test "$(uname)" = "Darwin"
            then
                ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
            elif test "$(expr substr $(uname -s) 1 5)" = "Linux"
            then
                ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
            fi

        fi

        exit 0
    else
        info "Homebrew/Linuxbrew already installed"
    fi
}
