#!/bin/sh
#
# This script will install Homebrew/Linuxbrew if it's not already present.

source $DOTHOME/lib/common

function install_brew () {
    if test ! $(which brew)
    then
        if test "$(uname)" = "Darwin"
        then
            user "Install Homebrew? (y/n)"
        else
            user "Install Linuxbrew? (y/n)"
        fi
        read -s -n 1 response
        if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
            if test "$(uname)" = "Darwin"
            then
                ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
            elif test "$(expr substr $(uname -s) 1 5)" = "Linux"
            then
                sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
            fi
        fi

        return
    else
        if test "$(uname)" = "Darwin"
        then
            info "Homebrew is already installed"
        else
            info "Linuxbrew is already installed"
        fi
    fi
}
