cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'git'
brew 'heroku'
brew 'heroku-toolbelt'
brew 'python'
brew 'thefuck'
brew 'tmux'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'iterm2'
cask 'hammerspoon'
cask 'p4merge'
cask 'visual-studio-code'
cask 'vlc'
cask 'lastpass'

